mdev

diff --git a/bin/sync b/bin/sync
--- a/bin/sync
+++ b/bin/sync
@@ -1,14 +1,84 @@
-#!/usr/bin/env bash
-
-mkdir project
- 
-mount_smbfs -o soft //test:test@mage.perf/share `pwd`/src
-
-#mount \
-#    -o port=62049,actimeo=5,proto=tcp,vers=4,noatime,async,hard,intr,rsize=81920,wsize=81920 \
-#    -t nfs 127.0.0.1: ./src
-
-echo "To unmount on MacOsX run"
-echo "diskutil unmountDisk force project"
+#!/bin/bash
+[[ ! ${MDEV_DIR} ]] && >&2 echo -e "\033[31mThis script is not intended to be run directly!\033[0m" && exit 1
 
 
+## attempt to install mutagen if not already present
+if ! which mutagen >/dev/null; then
+  echo -e "\033[33mMutagen could not be found; attempting install via brew.\033[0m"
+  brew install havoc-io/mutagen/mutagen
+fi
+
+## verify mutagen version constraint
+MUTAGEN_VERSION=$(mutagen version 2>/dev/null) || true
+MUTAGEN_REQUIRE=0.11.8
+if [[ $OSTYPE =~ ^darwin ]] && ! test $(m_version ${MUTAGEN_VERSION}) -ge $(m_version ${MUTAGEN_REQUIRE}); then
+  error "Mutagen version ${MUTAGEN_REQUIRE} or greater is required (version ${MUTAGEN_VERSION} is installed)."
+  >&2 printf "\nPlease update Mutagen:\n\n  brew upgrade havoc-io/mutagen/mutagen\n\n"
+  exit 1
+fi
+
+mutagen daemon start
+
+PROJECT_NAME=$(docker compose ls -q)
+
+## "${MDEV}" exec app killall mutagen-agent
+
+
+mutagen sync terminate --label-selector "$PROJECT_NAME"
+
+APP_CONTAINER=$(docker container inspect $(docker compose ps -q app) --format '{{ .Name }}')
+APP_CONTAINER="${APP_CONTAINER:1}"
+
+# sync files from local to docker immediately,
+# local is alpha here, so it will rewrite all your changes made on the docker side
+mutagen sync create src docker://${APP_CONTAINER}/magento \
+    --name "$PROJECT_NAME-to-docker" \
+    --label "$PROJECT_NAME" \
+    --symlink-mode=posix-raw \
+    --default-file-mode-beta=0666 \
+    --default-directory-mode-beta=0777 \
+    --sync-mode=one-way-replica  \
+    --watch-mode-beta=no-watch  \
+    --ignore=.idea \
+    --ignore=generated \
+    --ignore=app/etc \
+    --ignore=app/code/Magento/TestModule* \
+    --ignore=var \
+    --ignore=pub/media \
+    --ignore=pub/static \
+    --ignore=dev/tests/integration/tmp \
+    --ignore=dev/tests/acceptance/tests \
+    --ignore=vendor \
+    --ignore-vcs
+
+mutagen sync create docker://${APP_CONTAINER}/magento/app/etc  src/app/etc \
+    --name "$PROJECT_NAME-etc-from-docker" \
+    --label "$PROJECT_NAME" \
+    --symlink-mode=posix-raw \
+    --default-file-mode-beta=0666 \
+    --default-directory-mode-beta=0777 \
+    --sync-mode=two-way-resolved  \
+    --ignore=.idea \
+    --ignore-vcs
+
+mutagen sync create docker://${APP_CONTAINER}/magento/vendor  src/vendor \
+    --name "$PROJECT_NAME-vendor-from-docker" \
+    --label "$PROJECT_NAME" \
+    --symlink-mode=posix-raw \
+    --default-file-mode-beta=0666 \
+    --default-directory-mode-beta=0777 \
+    --sync-mode=one-way-replica  \
+    --watch-mode-beta=no-watch  \
+    --ignore=.idea \
+    --ignore-vcs
+
+mutagen sync create docker://${APP_CONTAINER}/magento/generated  src/generated \
+    --name "$PROJECT_NAME-generated-from-docker" \
+    --label "$PROJECT_NAME" \
+    --symlink-mode=posix-raw \
+    --default-file-mode-beta=0666 \
+    --default-directory-mode-beta=0777 \
+    --sync-mode=one-way-replica  \
+    --watch-mode-beta=no-watch  \
+    --ignore=.idea \
+    --ignore-vcs
